<!DOCTYPE html><html><head><base href="/"><title><#Web_Title#> - ShellCrash</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="-1"><link rel="shortcut icon" href="/images/favicon.ico"><link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css"><link rel="stylesheet" href="/bootstrap/css/main.css"><script src="/jquery.js"></script><script src="/state.js"></script><script src="/general.js"></script><script src="/popup.js"></script><style>#proxy-frame{display:block;width:100%;height:440px;border:0}#ui-status{padding:6px 14px;background:#fff;color:#798494;font-size:12px;border-bottom:1px solid #e1e7ef}#standalone{float:right}#tabMenu{display:none}</style><script>
var $j=jQuery.noConflict();
function initial(){
 show_banner(1);show_menu(7,window.shellCrashAnyTLSMenuIndex,1);show_footer();
 var frame=document.getElementById('proxy-frame'),origin=location.origin;
 window.addEventListener('message',function(e){
  if(e.origin!==origin||e.source!==frame.contentWindow||!e.data)return;
  if(e.data.type==='shellcrash-height'&&typeof e.data.height==='number')frame.style.height=Math.min(18000,Math.max(340,e.data.height+4))+'px';
  if(e.data.type==='shellcrash-connected')document.getElementById('ui-status-text').textContent='\u5df2\u81ea\u52a8\u8fde\u63a5 \u00b7 \u9009\u62e9\u5730\u533a\u548c\u5177\u4f53\u8282\u70b9';
 });
 document.getElementById('standalone').href=origin+'/custom/AnyTLSUI.asp?v=shellcrash-sites1';frame.src=origin+'/custom/AnyTLSUI.asp?embedded=1&v=shellcrash-sites1';
}
</script></head><body onload="initial();"><div class="wrapper"><div class="container-fluid" style="padding-right:0px"><div class="row-fluid"><div class="span3"><center><div id="logo"></div></center></div><div class="span9"><div id="TopBanner"></div></div></div></div><div id="Loading" class="popup_bg"></div><iframe name="hidden_frame" id="hidden_frame" src="" width="0" height="0" frameborder="0"></iframe><div class="container-fluid"><div class="row-fluid"><div class="span3"><div class="well sidebar-nav side_nav" style="padding:0px"><ul id="mainMenu" class="clearfix"></ul><ul class="clearfix"><li><div id="subMenu" class="accordion"></div></li></ul></div></div><div class="span9"><div class="row-fluid"><div class="span12"><div class="box well grad_colour_dark_blue"><h2 class="box_head round_top">ShellCrash</h2><div class="round_bottom"><div class="row-fluid"><div id="tabMenu" class="submenuBlock"></div><div id="ui-status"><a id="standalone" target="_blank" rel="noopener">独立打开管理页</a><span id="ui-status-text">正在自动连接管理服务…</span></div><iframe id="proxy-frame" title="ShellCrash"></iframe></div></div></div></div></div></div></div></div><div id="footer"></div></div></body></html>
